name: 'Common Setup'
description: 'Sets up common parts needed in all actions'

runs:
  using: "composite"
  steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dotnet tools
      shell: bash
      run: dotnet tool restore

    - name: Generate template code
      shell: bash
      run: dotnet t4 -o src/Runtime/Templates/Calls.cs src/Runtime/Templates/Calls.tt