name: Checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Set up
        uses: ./.github/actions/common-setup

      - name: Run tests
        run: dotnet test