name: Releasables

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Set up
        uses: ./.github/actions/common-setup

      - name: Build nupkg
        run: dotnet pack . --output nupkg

      - name: Archive nupkg
        uses: actions/upload-artifact@v3
        with:
          name: nupkg
          path: src/nupkg/*
          if-no-files-found: error

      - name: Build Unity dlls
        run: dotnet build SourceGenerator.Unity/SourceGenerator.Unity.csproj -c Release -o ./UnityDlls
      
      - name: Archive Unity dlls
        uses: actions/upload-artifact@v3
        with:
          name: UnityDlls
          path: |
            src/UnityDlls/*.dll
            src/UnityDlls/*.pdb
          if-no-files-found: error